export { classifyTask } from "./classifier"
export type { ClassifyResult } from "./classifier"
export type { ModelRef, TaskTier, TaskClassifier } from "./constants"
export { TASK_CLASSIFIERS, DEFAULT_TIER, DEFAULT_MODEL, DEFAULT_FALLBACK_MODELS } from "./constants"
export { LEXICON } from "./lexicon"
export type { Signal, SignalCategory, Lang, TierLexicon } from "./lexicon"
export { scoreText } from "./matcher"
export type { MatchResult, SignalHit, TierScore } from "./matcher"
export { createTaskClassifierHook } from "./hook"
